### ISSUE TITLE
Configurable VAT rate for products

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#1406]
We're going to be selling a lower self-service "sponsorship" tier through the website. As this does not entitle the sponsor to anything other than a mention on the website, it is outside the scope of VAT.

* There should be a VAT rate column on the product. This should default to a value which is set in the configuration (currently 20%).
* This column can be nullable where null means "VAT Exempt"
* The receipt/VAT invoice page needs to identify this and show the correct VAT amounts

We do ideally also need some report for this but that doesn't need to be part of this issue.

**Comment by Mattsi-Jansky** [comment]
I can give this a crack. Just to rephrase the requirements to make sure I understood correctly:

* Add a configurable VAT rate column
* On the invoice page, when the VAT rate column is null disable VAT altogether or otherwise set it to zero

I wonder if the new column could be a boolean instead, if the VAT rate is not likely to change per product? Something like `is_subject_to_vat`

**Comment by russss** [comment]
It turns out we do also need to handle items which are zero-rated for VAT (namely, children's T-shirts) and this is different from exempt, so I think it's probably best if we do have an actual rate column.

It might be best if we just use an enum ("Standard Rate", "Zero Rate", "Exempt") though, rather than putting the VAT rate in the column.

**Comment by marksteward** [comment]
I'd rather store the percent, in case we cross over with a VAT change in the future.

**Comment by russss** [comment]
I'm trying not to think about that possibility but if we do want to consider that then we probably need to store the VAT percentage on the price tier, not on the product. It gets complicated because there are potentially three zero-VAT states which we need to consider - zero-rated, exempt, and outside the scope. (Although I think exempt and outside the scope are functionally identical).

**Comment by russss** [comment]
Yup, I got it the wrong way round. Zero rated and exempt are functionally identical from our perspective. And donations are outside the scope, not exempt.

So we could do this with a nullable column where null means outside the scope, and I think it would be best to put it on the PriceTier.

**Comment by Mattsi-Jansky** [comment]
Made a start. Facing some issues with setting the default value from a configurable because the application configuration isn't available from the `models` scope, if I understood the following error right: 

```
models/product.py:273: in Product
    db.Float, nullable=True, default=app.config["DEFAULT_VAT_RATE"]
/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.11/lib/python3.11/site-packages/werkzeug/local.py:311: in __get__
    obj = instance._get_current_object()
/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.11/lib/python3.11/site-packages/werkzeug/local.py:508: in _get_current_object
    raise RuntimeError(unbound_message) from None
E   RuntimeError: Working outside of application context.
E
E   This typically means that you attempted to use functionality that needed
E   the current application. To solve this, set up an application context
E   with app.app_context(). See the documentation for more information.
make: *** [Makefile:15: test] Error 4
```

I'm not familiar enough with Flask to untangle this, so I'll default it to a static value for now. Making some progress in the `vat-exemption` branch

**Comment by marksteward** [comment]
Yeah, models are meant to be parseable without any state, and all the flask config stuff is wired up in [create_app](https://github.com/emfcamp/Website/blob/e6ffcb0/main.py#L99).

In this case it's probably best to explicitly set the default rate when creating a new Product (or PriceTier?), so [new_price_tier](https://github.com/emfcamp/Website/blob/e6ffcb0/apps/admin/products.py#L152) and the [fixture code](https://github.com/emfcamp/Website/blob/e6ffcb0/apps/tickets/tasks.py#L1530).

**Comment by Mattsi-Jansky** [comment]
How do we expect this field to effect the "VAT at 20%" field in the invoice? That is, if products can vary in their VAT rate and an invoice can contain multiple products, what do we say the overall VAT rate is?

![image](https://github.com/emfcamp/Website/assets/34603584/80efeecd-eada-49a0-aa44-b5214fb5aec3)

**Comment by Mattsi-Jansky** [comment]
Alright, that issue aside I've pushed some changes to calculate VAT on a per-product basis with changing VAT rates. Turns out I don't have push access so I forked the repo: https://github.com/emfcamp/Website/compare/main...Mattsi-Jansky:Emf-Website:vat-exemption

I manually tested it by opening various test receipts without my changes, then applying the changes and seeing the same result (with default VAT rate of `0.2`). If you change a product's VAT rate to zero it will reduce the amount of VAT displayed. It doesn't handle nulls yet.

However, the subtotal is calculated using `value_ex_vat`, which in turn is calculated by dividing a price by `1.2`. Since this value is static, it won't work in practice unless we also change this function to account for variable VAT rates - otherwise the amount paid will not match the invoice. It will be necessary to add a VAT column to the invoice table too, otherwise it may not be clear which line items have VAT and which ones don't.

I'm not sure this is the right approach. I'm still considering moving to a boolean or enum solution which seems a lot simpler. Let me know your thoughts.

**Comment by Mattsi-Jansky** [comment]
I moved the VAT rate to `PriceTier` and added the additional columns to the invoice. Because the database doesn't seem to support storing decimals I store the VAT rate as a string and convert it at runtime. Here's how it is looking:

Simple invoice with two tickets: 

![image](https://github.com/emfcamp/Website/assets/34603584/0ef3f1ac-b96a-418e-ad2d-919ef84cc57c)

Refunded invoice with two products, one of which has 0% VAT:

![image](https://github.com/emfcamp/Website/assets/34603584/3bfa622b-0a6f-452f-a0c8-cf977bb70ca5)

Does this look right? I'd also appreciate a double check on the math and the rounding logic in the following test. I decided to let the function return the raw decimal and format the result elsewhere if necessary:

```python
def test_calculating_price_ex_vat():
    tier = PriceTier(name="Tier 1", vat_rate="0.2")
    price = Price(currency="EUR", price_int=1000, price_tier = tier)
    assert round(price.value_ex_vat,2) == Decimal("8.33")
    price.value_ex_vat = Decimal("8.33")
    assert price.value == Decimal("9.99")

    tier.vat_rate = "0"
    price.value = Decimal("10")
    assert price.value_ex_vat == Decimal("10")
    price.value_ex_vat = Decimal("5")
    assert price.value == Decimal("5")
```

Changes are pushed in the same branch I linked before. Signing off now but I should be able to take another look tomorrow. Next I'll see if I can get the new field to be editable in the admin panel.
