### ISSUE TITLE
Inconsistent Information Location based on Login Status

### ISSUE THREAD

**Issue by MikeBookham** [emfcamp/Website#1645]
Currently, the location of information on the website changes depending on whether a user is logged in or not. This inconsistency can be confusing for users and hinder their experience.

For improved user experience, it is recommended to keep information in a consistent location across the website, regardless of the user's login state. This will make it easier for users to find what they need,  both when logged in and when browsing anonymously.

**Example of issue**
Logged out: volunteer -> food
Logged in: volunteer -> handbook -> food

**Comment by nomis** [comment]
The "volunteer" page when logged out shows the "volunteer intro" page, which has "food" on its vertical menu.

When logged in the "volunteer" page, it will give you one of the "volunteer" sub-pages depending on your sign-up state, along with a different set of horizontal menu options that only show up when logged in, but it doesn't show the vertical "handbook" menu.

The "handbook" then links to "volunteer intro" which will also show the horizontal volunteer menu options, but only then does the vertical "handbook" menu appear. Only this first page is recognised as being the "handbook" on the vertical menu.

If the horizontal menu was merged into the vertical menu so that everything is always available it'd work better.

(The mobile view doesn't have a vertical menu, it becomes another horizontal menu.)

**Comment by nomis** [comment]
Note: you have to be signed up to volunteer before this becomes a problem, otherwise it will take you to the handbook
