### ISSUE TITLE
Homepage management (pre-event)

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#206]
"website needs to be designed around the info people need at the time
days before the event front page should have location, travel, packing, instructions such as workshop booking, village booking, volunteering
during it should have info about DKs, current day schedule (possibly whats on and next), links to streams, power and internet usage :), lost property instructions, latest updates/tweets
after have thanks, photos, tilda sales, etc"

This should be automatic - different templates for different stages of the event that we can prepare in advance.

**Comment by russss** [comment]
For the on-site stuff I think it's probably best to serve a different page if you're accessing through the EMF IP range.

For other stuff it would be good to have a number of homepage states and switch between them based on a date schedule though:

- Save-the-date
- Ticket sales open
- Sales closed/during event (with IP-based redirection if you're on site, otherwise "no you can't buy tickets on the gate")
- Thanks for coming/see you next time

I'd especially like not to have to write/deploy the last one while sitting in a field this time

**Comment by russss** [comment]
Changing this ticket to just cover the following states:

* Pre ticket sales (i.e. the current page)
* Ticket sales, with tickets available.
* Ticket sales, with tickets currently unavailable (i.e. current batch of tickets sold out).
* Ticket sales, sold out.
