### ISSUE TITLE
Create an account for each ticketholder

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#212]
It's likely that our account system will be used for other functions (volunteering, etc), so really we need to give every ticketholder an account, rather than just the ticket purchaser. (See also #205.)

**Comment by marksteward** [comment]
Also vital for communications. Make it simple to transfer tickets in advance.

**Comment by SamLR** [comment]
So we'll need some method of tracking transfer of tickets.

**Comment by marekventur** [comment]
I'm currently looking at this. I've removed the requirement for a login for the first two pages and now I'm on ```/tickets/info``` where we ask for volunteering and accessibility requirements. I guess this is a good place to ask for email addresses. 

Should we:
1) Ask for one email address per ticket and make that field mandatory and unique? (This is probably a no-go since it creates problems for families with children and people who don't yet know who exactly is coming with them)
2) or ask for one email address per ticket and make only the first field mandatory and unique?
3) or ask for one email address per checkout and provide some means to assign email addresses to tickets later?

While 3) is relatively straightforward ("we need your email address to send you the ticket") 1) and 2) will require some more explanation along the lines of "Please provide us with the email addresses of the other attendees so we can allow them to create accounts to sign up to workshops and other activities once they become available". 

Also: Should there be a link a'la "sign up now" on that page or shall we query for that at a later point?

Thoughts?

**Comment by marekventur** [comment]
Current work in progress, it's basically option 2) from my suggestions above. Any thoughts? (I'm terrible at copy, I hope someone can come up with better words)

![suggestion](https://cloud.githubusercontent.com/assets/158185/9564771/26280ca4-4ea8-11e5-9bea-f61e629838d8.png)

I've also realised that I'm working on two different tickets at the same time: This one and the "allow tickets to be bought without signing up first." (part of #211). I will keep them separate and create two PRs for them.

**Comment by marksteward** [comment]
2 is my preferred option, for what that's worth, and the screenshot looks about right. Don't worry if separating the two tickets is awkward - I think you're the only person working on that flow right now.

**Comment by SamLR** [comment]
Happy with 2) as well. As to the design I think an earlier iteration allowed you to hide all the explanatory text (I think it used the Bootstrap 2 inline help thing which got eaten in the upgrade to BS3).

As part of this I can image that there are some people that don't have an email and/or are young children. How will they sign up for workshops? We dodged this with volunteers by requiring an email but I don't think we can reasonably pull that off in the case of workshops: names only?

**Comment by marksteward** [comment]
That's a good point - so we might need to create any number of shell users for workshops only (volunteering shifts shouldn't be open to people who can't be notified). Alternatively or additionally, make it easy for people to look up friends/family.

**Comment by SamLR** [comment]
Is this now closed by #225 etc?

**Comment by russss** [comment]
I think #225 and transfers fixes this sufficiently for the moment, but it's likely we might have to do a bit more work pre-event.
