### ISSUE TITLE
Talks (/performances), workshops and installations blurb

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#301]
Each tab of the CfP form should have a (short) blurb at the top describing what is expected for that type of submission.

As part of this it should make it clear that 'performances' comes under the purvey of 'talks' (rename the tab heading)

**Comment by russss** [comment]
I took a look at this, but I think it's probably best to keep the text on the actual tab to the minimum level required to actually assist the user in filling in the form. (I think we should assume that once they're reading the form, they've already made the decision to submit a proposal.)

I don't think it's clear what information we feel we need to convey which we aren't doing currently, because it didn't feel like the info at the top of the tabs was adding much.

Tab heading is renamed now.
