### ISSUE TITLE
Get rid of python2

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#534]
Placeholder issue

**Comment by russss** [comment]
According to pyup.io, we have 9 modules which are incompatible with python3 (or rather, which are not known to be compatible):

- [ ] inlinestyler
- [ ] Flask-DebugToolbar
- [ ] py-bcrypt
- [ ] cssmin
- [ ] Flask-Mail
- [ ] httplib2
- [ ] gocardless (this will be fixed by #535)
- [ ] fake-factory
- [ ] pulp (there is a py3 fork [here](https://pypi.python.org/pypi/PuLP-py3))

**Comment by russss** [comment]
This is done, at least initially.
