### ISSUE TITLE
End-of-event export and display of persistent data

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#538]
There should be a way of exporting all data we want to preserve to static files, so the website can display info about talks from previous events, and for whatever reasons we want.

The website needs to pull talk data for previous years from these static files.

**Comment by Jonty** [comment]
Notes from sam & I, will make this more readable ASAP:

* Summary of diversity information
* Contact information of those who submitted to the CfP & were accepted
* Summary information for tickets
   * Types sold
   * States
   * Date information
   * Check-in timestamps
* Payments
   * Refunds
   * Cancels
   * Datetime
   * Amount
   * Currency
   * Method
   * Time to pay
* Ical - grab everything (except phone number/email)
* Email
   * All jobs
* Cfp
   * title/description
   * Name
   * when/where
   * Offline contact
   * Speaker’s availability summary
      * Talk + length
   * Notice required
   * Summary of £ requests
      * Info on number requests/person ?
   * arrival/dept times
   * Is recording ok?
   * Requires laptop?
* Favourites
   * Anon user

**Comment by Jonty** [comment]
We also need to keep times that tickets were checked in, by ticket type (adult, kid, badge)

**Comment by marksteward** [comment]
I'm not going to save "anon user" favourites, as I think that's creepy. I can do a matrix of "how many people liked both these talks" if you like.

When you say Payments above, do you mean you need a dump of everything, or will the summary stuff I've taken so far suffice? Time to pay is the one outstanding thing for me to do otherwise.

Are all those details needed for all accepted Proposals, or only a subset?

**Comment by marksteward** [comment]
Export done by 9bde7e3, previous year schedule is now #572
