### ISSUE TITLE
VAT invoice improvements

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#662]
To avoid ambiguity.

**Comment by russss** [comment]
This is actually a bit more complex so I'm going to write some things to help me think about it.

* VAT invoices need a monotonically increasing invoice number, although we can use a different sequence for each year.
* If we issue a VAT invoice, we need to keep a copy of it (even if we cancel/refund the order) for six years.
* We only need to issue VAT invoices to VAT-registered customers on request. 
* The VAT invoice must include the customer's name and address.

Given this, we should probably only issue VAT invoices on request. Otherwise we're unnecessarily saving peoples' personal details.

One option would be to use the Xero API to issue these invoices. They'd then use the same invoice sequence as the rest of the invoices we issue. However, this would complicate the accounting quite a bit, especially when it comes to VAT, so I'm not keen on this.

Simplest solution is probably:
* Flag our existing receipts as "NOT A VAT INVOICE".
* Add a form to request a VAT invoice. This will ask for name and address, and will save a PDF of the invoice to disk. We can then collect these saved invoices and archive them after the event.

We also need to export a ledger for VAT recordkeeping. This should include, for all purchases:
* Date/time of purchase
* Net value of purchase
* VAT rate

It doesn't require name or any personal details.
