### ISSUE TITLE
Schedule should clearly show which talks aren't going to be recorded

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#682]

**Comment by jellybob** [comment]
Having added this in the form of an icon on any content which isn’t going to be recorded I’m leaning towards highlighting the ones that will be recorded instead. This approach is fine when limiting to only talks at official venues, but once we bring in village content, workshops, performances etc there’s a lot of icon noise because none of that content is flagged as being recorded.

**Comment by jellybob** [comment]
The alternative here is to only show the icon on main venue talks which aren’t going to be recorded, but I’m not sure if that will cause people to assume everything else will be available online later.

**Comment by kliment** [comment]
I think people can reasonably assume no village content will be recorded and we can use the icons only for the main venues (anything that doesn't have VOC presence should not have icons of any kind imo). Alternatively, we can have recording/no recording icons for all main venue talks and no indicator on the village content.
