### ISSUE TITLE
Require explicit choice for "I need a laptop" question during CfP finalisation

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#828]
From #812:

> Default for checkbox for needing use of laptop should be unchecked but required (this came up in 2018)

**Comment by jayaddison** [comment]
Is it worth adding a little more description for this issue?  The way it reads to me is that the 'requires laptop' option must be either `true` or `false` for the form to be submitted, but should begin in a null/unset state (i.e. the person updating the talk entry has to make an explicit selection, rather than skipping/ignoring the field and accepting the default).

**Comment by russss** [comment]
Yup, that's correct. I guess we'll need to change it to using unselected radio buttons.

**Comment by marksteward** [comment]
Preferably styled with bootstrap ala https://getbootstrap.com/docs/4.0/components/buttons/#checkbox-and-radio-buttons
