### ISSUE TITLE
SEPA payment references should be ISO 11649 Creditor References

### ISSUE THREAD

**Issue by davidc** [emfcamp/Website#878]
SEPA payment references should be amended to be ISO 11649 Creditor References, with "RF" and with two check digits added to the start.

This will allow the user's bank to verify the reference prior to the payment being sent to avoid typos.

Needs amending anywhere references are displayed (not necessary to change how they are stored in the database) plus any bank recon needs to accept both formats.

**Comment by russss** [comment]
We can't do this while using Barclays for Euro banking as they severely truncate references leaving us as few as 2 characters to work with. So this depends at least on #857.

**Comment by davidc** [comment]
This should not apply when giving BACS transfer details as it will run into reference length issues (and probably wouldn't be validated anyway)

**Comment by jayaddison** [comment]
See https://wiki.xmldation.com/General_Information/ISO11649_-_Creditor_Reference for some details on the check digit algorithm.

There are a few libraries in various languages [on github](https://github.com/search?q=ISO+11649&type=Repositories) which may be able to validate/generate this format.

**Comment by jayaddison** [comment]
> There are a few libraries in various languages [on github](https://github.com/search?q=ISO+11649&type=Repositories) which may be able to validate/generate this format.

For future reference - [python-stdnum](https://arthurdejong.org/python-stdnum/) seems to be a good library for calculating and validating check digits of all kinds, including ISO 11649.

**Comment by jayaddison** [comment]
I've begun some work for this, generating ISO-11649 creditor references that are 16 characters in length total (including the `RFXX` prefix, and then a 12-character reference part).

The draft implementation is naive, and the reference part currently consists of (all base-10) the event year number YYYY followed by a zero-padded 8-digit order number.

I'm not sure that format is ideal, and as follow-ups I'm considering:

* Reversibly encode the existing `BankPayment.bankref` instead of the `Payment.id` - this should be backwards-compatible with existing bank transaction reconcilation if done correctly.
* Consider using base36 encoding for the reference part, allowing for more concise creditor references.
* Consider not zero-padding the reference part, again providing more concise creditor references (ref: [Finland Finance intro to structured creditor references](https://www.finanssiala.fi/wp-content/uploads/2021/03/Introduction_of_the_global_Structured_Creditor_Reference.pdf#page=10)).
* Add a plaintext-readable (non-QR-encoded) copy of the structured reference on the invoice and/or on an edge of the QR code to provide an additional manual verification check (ref [this online EPC QR generator](https://epc-qr.eu/?form) which does this).
