### ISSUE TITLE
Allow refund system to be used for normal refunds

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#900]
The refund system is a bit opaque at the moment and we should make this clearer to the ticket purchaser. If they request a refund for a payment, they should be able to select which specific tickets they'd like refunded. We should show the total amount of the refund.

Users should not be able to request a refund for tickets they have transferred to other people (we should ask them to transfer those tickets back before requesting a refund). This requirement should not apply in the case that the event is cancelled - in this case (only) the original purchaser should be able to request a refund for the full amount of their payment.

Users should not be able to request a refund for checked-in tickets. We can do this through the backend in exceptional circumstances.

I'm doing some initial work for this while sorting out 2020 refunds but I'm only concerned about the (unusual) cancellation refund flow in this case.

**Comment by russss** [comment]
Other thoughts which have just occurred to me:

* User should have an option to cancel the refund request.
* Refund request should be cancelled if any tickets are transferred or checked in.

**Comment by SamLR** [comment]
There should be a state machine for refunds with the following states:
* off
* on
* illness-only
* cancellation

**Comment by SamLR** [comment]
New plan (moving to `better-self-refund` branch)

* Add state machine
  * off - no refund buttons etc visible to users
  * on - refund available to all, the 'request refund' button leads to a form where viable tickets can be selected for refund
    * ticket returned to pool
  * illness-only - refund still available but copy change to indicate that should only be used b/c you're ill
    * ticket returned to pool
  * cancellation - refund button goes to 'donation' slider rather than ticket select
* Form & POST should check whether a ticket is refundable (this is a property of the ticket? current user == owner (not transferred) && state machine && not checked in)
